version: "2"
services:
  postgres:
    image: postgres
    volumes:
      - ../data/postgres/data:/var/lib/postgresql/data
      - ../logs/postgres:/var/log/postgresql
  nginx-proxy:
    image: nginx
    ports: 
      - "8080:80"
    volumes:
      - ../config-files/nginx/conf.d:/etc/nginx/conf.d
      - ../logs/nginx:/var/log/nginx
  pgadmin:
    image: dpage/pgadmin4
    volumes:
      - ../data/pgadmin:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=monty.python@example.com
      - PGADMIN_DEFAULT_PASSWORD=hello1234
      - PGADMIN_LISTEN_PORT=8080
